"""
Peewee Database Models
=======================
Persistent database schema for trades, signals, and metrics using Peewee ORM.

Provides:
- Trade history with entry/exit prices and P&L
- Trading signals with timestamps and validations
- Agent execution history and metrics
- News and sentiment history

Usage:
    from peewee_models import get_db, Trade, Signal, create_tables
    
    # Initialize database
    db = get_db()
    create_tables()
    
    # Create trade record
    trade = Trade.create(
        symbol="XAUUSD",
        entry_price=2045.50,
        exit_price=2050.25,
        quantity=0.1,
        pnl=47.5,
        status="closed"
    )
    
    # Query trades
    closed_trades = Trade.select().where(Trade.status == "closed")
    total_pnl = sum(t.pnl for t in closed_trades)
"""

import os
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any
from enum import Enum

from peewee import (
    SqliteDatabase, Model, CharField, FloatField, IntegerField,
    DateTimeField, BooleanField, TextField, ForeignKeyField, fn
)
from playhouse.sqlite_ext import JSONField

from logger import get_logger

logger = get_logger(__name__)


# ─────────────────────────────────────────────────────
# Database Configuration
# ─────────────────────────────────────────────────────

DB_PATH = os.path.join("data", "clawgold.db")
os.makedirs("data", exist_ok=True)

db = SqliteDatabase(DB_PATH)


# ─────────────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────────────

class TradeStatus(str, Enum):
    """Trade status states."""
    PENDING = "pending"
    OPEN = "open"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class SignalStatus(str, Enum):
    """Signal status states."""
    ACTIVE = "active"
    EXECUTED = "executed"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


# ─────────────────────────────────────────────────────
# Base Model
# ─────────────────────────────────────────────────────

class BaseModel(Model):
    """Base model with common timestamp fields."""
    created_at = DateTimeField(default=datetime.now)
    updated_at = DateTimeField(default=datetime.now)
    
    class Meta:
        database = db
    
    def save(self, *args, **kwargs):
        """Update timestamp on save."""
        self.updated_at = datetime.now()
        return super().save(*args, **kwargs)


# ─────────────────────────────────────────────────────
# Trade Model
# ─────────────────────────────────────────────────────

class Trade(BaseModel):
    """Completed or in-progress trade record."""
    
    symbol = CharField(default="XAUUSD", help_text="Trading symbol (XAUUSD)")
    status = CharField(default=TradeStatus.OPEN, help_text="Trade status")
    
    # Entry details
    entry_price = FloatField(help_text="Entry price (USD)")
    entry_time = DateTimeField(default=datetime.now, help_text="Entry timestamp")
    entry_reason = TextField(default="", help_text="Why entered (signal description)")
    
    # Exit details
    exit_price = FloatField(null=True, help_text="Exit price (USD)")
    exit_time = DateTimeField(null=True, help_text="Exit timestamp")
    exit_reason = TextField(default="", help_text="Why exited (TP/SL/manual)")
    
    # Position details
    quantity = FloatField(help_text="Position size (lots)")
    leverage = IntegerField(default=1, help_text="Leverage used")
    
    # Risk management
    stop_loss = FloatField(null=True, help_text="Stop loss level")
    take_profit = FloatField(null=True, help_text="Take profit level")
    
    # Performance
    pnl = FloatField(default=0.0, help_text="Profit/Loss (USD)")
    pnl_percent = FloatField(default=0.0, help_text="Profit/Loss %")
    
    # Metadata
    metadata = JSONField(default={}, help_text="Custom metadata (strategy, etc.)")
    
    class Meta:
        table_name = "trades"
    
    def calculate_pnl(self):
        """Calculate P&L if exit price is set."""
        if self.exit_price:
            pnl = (self.exit_price - self.entry_price) * self.quantity * 100
            pnl_pct = ((self.exit_price - self.entry_price) / self.entry_price) * 100
            self.pnl = pnl
            self.pnl_percent = pnl_pct
            return pnl
        return 0.0


# ─────────────────────────────────────────────────────
# Signal Model
# ─────────────────────────────────────────────────────

class Signal(BaseModel):
    """Trading signal generated by AI agents."""
    
    symbol = CharField(default="XAUUSD")
    signal_type = CharField(help_text="BUY, SELL, HOLD, NEUTRAL")
    confidence = FloatField(help_text="Confidence 0-1")
    status = CharField(default=SignalStatus.ACTIVE)
    
    # Signal details
    reason = TextField(help_text="Why this signal")
    target_price = FloatField(null=True, help_text="Target price")
    stop_loss = FloatField(null=True, help_text="Recommended SL")
    
    # Execution
    executed = BooleanField(default=False, help_text="Was this signal traded?")
    executed_time = DateTimeField(null=True, help_text="When trade was executed")
    trade = ForeignKeyField(Trade, null=True, backref="signals", help_text="Associated trade")
    
    # Quality tracking
    quality_score = FloatField(null=True, help_text="Post-mortem quality score 0-1")
    actual_outcome = CharField(null=True, help_text="Actual result (profitable/loss/neutral)")
    
    # Metadata
    agent = CharField(default="", help_text="Agent that generated signal")
    metadata = JSONField(default={})
    
    class Meta:
        table_name = "signals"


# ─────────────────────────────────────────────────────
# Agent Execution Model
# ─────────────────────────────────────────────────────

class AgentExecution(BaseModel):
    """Record of AI agent task execution."""
    
    task_name = CharField(help_text="Task executed (daily_report, etc.)")
    agent = CharField(help_text="Agent name (researcher, analyst, etc.)")
    tool = CharField(help_text="Tool used (opencode, gemini, etc.)")
    
    # Execution details
    prompt = TextField(help_text="Input prompt")
    response = TextField(help_text="Generated response")
    
    # Performance
    duration_ms = IntegerField(help_text="Execution time in milliseconds")
    tokens_in = IntegerField(default=0, help_text="Input tokens")
    tokens_out = IntegerField(default=0, help_text="Output tokens")
    cost_usd = FloatField(default=0.0, help_text="API cost in USD")
    
    # Status
    success = BooleanField(default=True, help_text="Did execution succeed?")
    error_message = TextField(default="", help_text="Error if failed")
    
    # Evaluation
    quality_score = FloatField(null=True, help_text="Quality evaluation 0-1")
    
    # Metadata
    metadata = JSONField(default={})
    
    class Meta:
        table_name = "agent_executions"
    
    @classmethod
    def log_execution(cls, task_name: str, agent: str, tool: str, 
                      prompt: str, response: str, duration_ms: int,
                      tokens_in: int = 0, tokens_out: int = 0, cost: float = 0.0,
                      success: bool = True, error: str = ""):
        """Convenience method to log an execution."""
        return cls.create(
            task_name=task_name,
            agent=agent,
            tool=tool,
            prompt=prompt,
            response=response,
            duration_ms=duration_ms,
            tokens_in=tokens_in,
            tokens_out=tokens_out,
            cost_usd=cost,
            success=success,
            error_message=error,
        )


# ─────────────────────────────────────────────────────
# News Model
# ─────────────────────────────────────────────────────

class NewsItem(BaseModel):
    """News articles for market analysis."""
    
    title = TextField(help_text="Article title")
    content = TextField(help_text="Article summary")
    source = CharField(help_text="News source (Reuters, Bloomberg, etc.)")
    url = CharField(null=True, help_text="Source URL")
    
    # Classification
    symbol = CharField(default="XAUUSD")
    sentiment = CharField(default="neutral", help_text="bullish/bearish/neutral")
    impact_score = FloatField(default=0.5, help_text="Impact importance 0-1")
    
    # Content
    keywords = JSONField(default=[], help_text="Extracted keywords")
    metadata = JSONField(default={})
    
    # Timing
    published_at = DateTimeField(help_text="Article publish time")
    
    class Meta:
        table_name = "news"


# ─────────────────────────────────────────────────────
# Sentiment Model
# ─────────────────────────────────────────────────────

class SentimentRecord(BaseModel):
    """Sentiment analysis results over time."""
    
    symbol = CharField(default="XAUUSD")
    timeframe = CharField(help_text="M15, H1, H4, D1, etc.")
    
    # Sentiment metrics
    overall_sentiment = FloatField(help_text="Aggregated sentiment -1 to 1")
    bullish_count = IntegerField(help_text="Bullish signals")
    bearish_count = IntegerField(help_text="Bearish signals")
    neutral_count = IntegerField(help_text="Neutral signals")
    
    # Analysis
    reasoning = TextField(help_text="Why this sentiment")
    confidence = FloatField(help_text="Confidence 0-1")
    
    # Data
    metadata = JSONField(default={})
    
    class Meta:
        table_name = "sentiment_records"


# ─────────────────────────────────────────────────────
# Metrics Model
# ─────────────────────────────────────────────────────

class DailyMetrics(BaseModel):
    """Daily performance metrics."""
    
    date = DateTimeField(unique=True, help_text="Date of metrics")
    
    # Trade metrics
    trades_count = IntegerField(default=0)
    winning_trades = IntegerField(default=0)
    losing_trades = IntegerField(default=0)
    win_rate = FloatField(default=0.0, help_text="% of winning trades")
    
    # P&L metrics
    total_pnl = FloatField(default=0.0, help_text="Daily P&L in USD")
    max_profit = FloatField(default=0.0, help_text="Best trade P&L")
    max_loss = FloatField(default=0.0, help_text="Worst trade loss")
    
    # Cost metrics
    api_cost = FloatField(default=0.0, help_text="Daily API costs")
    agent_calls = IntegerField(default=0, help_text="Number of AI calls")
    
    # Risk metrics
    max_drawdown_pct = FloatField(default=0.0)
    risk_reward_ratio = FloatField(default=0.0)
    
    class Meta:
        table_name = "daily_metrics"


# ─────────────────────────────────────────────────────
# Database Utilities
# ─────────────────────────────────────────────────────

def get_db() -> SqliteDatabase:
    """Get database instance."""
    return db


def create_tables():
    """Create all tables."""
    db.create_tables([
        Trade, Signal, AgentExecution,
        NewsItem, SentimentRecord, DailyMetrics
    ], safe=True)
    logger.info(f"[Peewee] Tables created/verified at {DB_PATH}")


def drop_tables():
    """Drop all tables (destructive)."""
    db.drop_tables([
        Trade, Signal, AgentExecution,
        NewsItem, SentimentRecord, DailyMetrics
    ], safe=True)
    logger.warning("[Peewee] All tables dropped")


# ─────────────────────────────────────────────────────
# Query Helpers
# ─────────────────────────────────────────────────────

class QueryHelpers:
    """Common query patterns."""
    
    @staticmethod
    def get_trades_today() -> List[Trade]:
        """Get all trades from today."""
        today = datetime.now().date()
        return Trade.select().where(
            fn.DATE(Trade.created_at) == today
        )
    
    @staticmethod
    def get_total_pnl(days: int = 7) -> float:
        """Get total P&L for last N days."""
        cutoff = datetime.now() - timedelta(days=days)
        trades = Trade.select().where(
            (Trade.status == TradeStatus.CLOSED) &
            (Trade.created_at >= cutoff)
        )
        return sum(t.pnl for t in trades)
    
    @staticmethod
    def get_win_rate(days: int = 7) -> float:
        """Calculate win rate for last N days."""
        cutoff = datetime.now() - timedelta(days=days)
        trades = Trade.select().where(
            (Trade.status == TradeStatus.CLOSED) &
            (Trade.created_at >= cutoff)
        )
        trades = list(trades)
        if not trades:
            return 0.0
        winners = sum(1 for t in trades if t.pnl > 0)
        return winners / len(trades)
    
    @staticmethod
    def get_recent_signals(limit: int = 10) -> List[Signal]:
        """Get recent trading signals."""
        return Signal.select().order_by(Signal.created_at.desc()).limit(limit)
    
    @staticmethod
    def get_agent_stats(tool: str, days: int = 7) -> Dict[str, Any]:
        """Get stats for an AI tool."""
        cutoff = datetime.now() - timedelta(days=days)
        executions = AgentExecution.select().where(
            (AgentExecution.tool == tool) &
            (AgentExecution.created_at >= cutoff)
        )
        executions = list(executions)
        
        if not executions:
            return {}
        
        total_cost = sum(e.cost_usd for e in executions)
        avg_cost = total_cost / len(executions)
        success_rate = sum(1 for e in executions if e.success) / len(executions)
        avg_duration = sum(e.duration_ms for e in executions) / len(executions)
        
        return {
            'tool': tool,
            'calls': len(executions),
            'total_cost': total_cost,
            'avg_cost': avg_cost,
            'success_rate': success_rate,
            'avg_duration_ms': avg_duration,
        }
